package com.tubus.driver.data.local

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * One GPS fix waiting to be uploaded. Written before any network attempt (README.md
 * "Offline behavior") — nothing is lost to a dropped request or a killed process.
 *
 * `clientPointId` has a unique index so `@Insert(onConflict = IGNORE)` actually has a
 * conflict to ignore — without one, a re-insert of the same id is just a second row
 * with a different autogenerated `id`, silently defeating the dedup the DAO's own
 * docs promise.
 */
@Entity(tableName = "queued_points", indices = [Index(value = ["clientPointId"], unique = true)])
data class QueuedPointEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val tripId: String,
    val clientPointId: String,
    val latitude: Double,
    val longitude: Double,
    val accuracyM: Float?,
    val speedMps: Float?,
    val bearingDeg: Float?,
    val deviceTimestampEpochMs: Long,
)
